### ISSUE TITLE
Is generic supported

### ISSUE THREAD

**Issue by xuegl** [swaggo/gin-swagger#205] opened 2022-04-20 08:00 UTC
I have a generic response type:
```go
type Response[T any] struct {
	ErrorCode    int    `json:"error_code"`
	ErrorMessage string `json:"error_message"`
	Data         T      `json:"data,omitempty"`
}
```
And use it to generate the swagger doc:
```go
// @Summary Get the component list
// @Description Get the component list, supporting pagination
// @Tags Component
// @Param page query int false "page number" default(0)
// @Param count query int false "page count" default(20)
// @Produce json
// @Success 200 {object} response.Response[[]Component] "component list"
// @Router /components [get]
func (h *DefaultHandler) getComponents(c *gin.Context) {
        ......
}
```
But when i tries to generate swagger doc, it reports below error:
```
2022/04/20 15:49:43 Generate swagger docs....
2022/04/20 15:49:43 Generate general API Info, search dir:./
2022/04/20 15:50:04 ParseComment error in file /path/to/components/controller.go :cannot find type definition: response.Response[[]Component]
```
So i guess that generic is not supported. Is this case?

**Comment by ubogdan** [comment] 2022-04-20 10:46
You're right. The response contains a generic definition and swag doesn't have yet support for it.

**Comment by mikem-zed** [comment] 2022-04-20 13:13
the issue is already closed in swag repo https://github.com/swaggo/swag/issues/1162

**Comment by ubogdan** [comment] 2022-04-20 18:47
@mikem-zed this is an open-source project feel free to contribute if you want to give a hand. The issue you are pointing at wont giving errors in cases like the following
```go
type response struct {
     Data any
}
```

**Comment by ubogdan** [comment] 2022-04-20 18:49
@xuegl I didn't realize when I replied to you. Please re-open this issue in the right place https://github.com/swaggo/swag/issues.

**Closed by ubogdan** 2022-04-20 18:49 UTC
